### ISSUE TITLE
when navigating to a smithy file in a jar, an exception is generated

### ISSUE THREAD

**Issue by daddykotex** [disneystreaming/smithy-language-server#19]
It works, but we can see in the output the following exception:

```
[2022-02-22 14:40:17.444] [renderer6] [error] [Extension Host] stderr: Feb 22, 2022 2:40:17 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "textDocument/didClose",
  "params": {
    "textDocument": {
      "uri": "smithyjar:/c%3A/Users/dfrancoeur/AppData/Local/Coursier/cache/v1/https/repo1.maven.org/maven2/com/disneystreaming/smithy4s/smithy4s-protocol_2.13/0.12.2/smithy4s-protocol_2.13-0.12.2.jar%21/META-INF/smithy/smithy4s.smithy"
    }
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.IllegalArgumentException: URI scheme is not "file"
	at java.io.File.<init>(File.java:421)
	at software.amazon.smithy.lsp.SmithyTextDocumentService.fileFromUri(SmithyTextDocumentService.java:333)
	at software.amazon.smithy.lsp.SmithyTextDocumentService.fileUri(SmithyTextDocumentService.java:325)
	at software.amazon.smithy.lsp.SmithyTextDocumentService.didClose(SmithyTextDocumentService.java:312)
	... 16 more
```

**Comment by kubukoz** [comment]
@daddykotex do you mind checking if this still happens? I couldn't reproduce.
